### ISSUE TITLE
[iOS] Doesn't display in standalone?

### ISSUE THREAD

**Issue by sedubois** [NekR/offline-plugin-pwa#1]
Hi! I just discovered this promising project 🙂 First thing I tested is opening https://offline-plugin.now.sh on my iPhone, then "add to homescreen", then clicking the created shortcut. The shortcut has the proper name and icon, but the page opens in a browser tab instead of as a standalone app, despite the fact that [manifest.json has `"display": "standalone"`](https://github.com/NekR/offline-plugin-pwa/blob/master/src/favicons/manifest.json#L18).

I'm new to PWAs, am I missing something?

**Comment by NekR** [comment]
Hi! Safari doesn't yet exactly support PWA, so neither ServiceWorker nor `manifest.json` work/supported there. Hence that property doesn't affect the Safari. If you try to add it to home screen on Android, it will be in standalone mode.

Safari supports standalone mode with another way, by specifying  `<meta name="apple-mobile-web-app-capable" content="yes">` tag. I'm not sure why I didn't do that. Standalone mode in Safari is a bit buggy so often I prefer to not use it, so maybe I just forgot it now.

Do you think it makes sense to add it?

**Comment by sedubois** [comment]
Thanks I think it makes sense to add it, yes :) even if imperfect, I think it's a really nice improvement, to view a webapp without toolbars around it (I'm building a meditation timer so really want distractions out of the way).

**Comment by sedubois** [comment]
Has Apple got any ETA on supporting manifest.json or even intention to support it?

**Comment by NekR** [comment]
There is no ETA or any signals from Apple about supporting `manifest.json`. Also ServiceWorker is only "Under Consideration", so there chances that they won't support it at all or may start support it in 5 years. Who knows.

> I'm building a meditation timer so really want distractions out of the way

Are you using this demo as boilerplate for you app?

**Comment by NekR** [comment]
Okay, I made it standalone on iOS: https://github.com/NekR/offline-plugin-pwa/commit/c22b646b4f5364ce6d113b949914aa14e1d29cbd

**Comment by sedubois** [comment]
Thanks! Has this been deployed? Still doesn't display in standalone for me.

**Comment by NekR** [comment]
Yes, deployed. You need to re-add the shortcut.

**Comment by sedubois** [comment]
Yes I had done that. But ok this time it works for some reason, thanks :)

**Comment by NekR** [comment]
Seems like you didn't wait for AppCache update to be received before re-adding the shortcut :-)
