### ISSUE TITLE
Content of favicons folder isn't favicons

### ISSUE THREAD

**Issue by sedubois** [NekR/offline-plugin-pwa#2]
E.g contains `manifest.json`. Was confusing me at first, as I didn't find `manifest.json`. Then I saw how `CopyWebpackPlugin` was calling it.

How about moving non-favicon files to the parent folder?

(not critical of course)

**Comment by NekR** [comment]
Not sure what you mean. On build `CopyWebpackPlugin ` extracts everything from `favicons/` folder directly to `dist/` folder.

**Comment by sedubois** [comment]
Yes. But `manifest.json` is in that favicons folder, although obviously that file isn't a favicon. E.g it handles other things like configuring the name of the app and whether it should display in standalone.

Anyway it's nothing critical, was just confusing to me.

**Comment by NekR** [comment]
I think you just overthinking it. All is in that folder because all of that is generated at once by https://realfavicongenerator.net/. And yes, `manifest.json` is favicon nor `browserconfig.xml`, etc. but it's being generated by favicon generator :-)

**Comment by sedubois** [comment]
Yes thanks 😄
